import abjad


metadata = abjad.TypedOrderedDict(
    [
        (
            'arch-a-score',
            abjad.TypedOrderedDict(
                [
                    (
                        'break_measures',
                        [
                            1,
                            8,
                            17,
                            30,
                            40,
                            51,
                            60,
                            75,
                            85,
                            97,
                            108,
                            125,
                            143,
                            155,
                            165,
                            178,
                            194,
                            208,
                            222,
                            235,
                            247,
                            252,
                            ],
                        ),
                    ]
                ),
            ),
        (
            'ledger-score',
            abjad.TypedOrderedDict(
                [
                    (
                        'break_measures',
                        [
                            1,
                            16,
                            33,
                            49,
                            63,
                            75,
                            85,
                            97,
                            108,
                            125,
                            143,
                            155,
                            165,
                            178,
                            194,
                            208,
                            222,
                            235,
                            247,
                            252,
                            ],
                        ),
                    ]
                ),
            ),
        ]
    )
