import abjad


metadata = abjad.TypedOrderedDict(
    [
        (
            'arch-a-score',
            abjad.TypedOrderedDict(
                [
                    (
                        'break_measures',
                        [
                            1,
                            8,
                            17,
                            30,
                            38,
                            49,
                            59,
                            69,
                            78,
                            86,
                            97,
                            104,
                            114,
                            123,
                            135,
                            145,
                            153,
                            160,
                            168,
                            177,
                            189,
                            197,
                            204,
                            212,
                            220,
                            229,
                            239,
                            247,
                            251,
                            ],
                        ),
                    ]
                ),
            ),
        (
            'ledger-score',
            abjad.TypedOrderedDict(
                [
                    (
                        'break_measures',
                        [
                            1,
                            16,
                            33,
                            49,
                            63,
                            75,
                            85,
                            97,
                            108,
                            125,
                            143,
                            155,
                            165,
                            178,
                            194,
                            208,
                            222,
                            235,
                            247,
                            252,
                            ],
                        ),
                    ]
                ),
            ),
        ]
    )
