import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Ensemble_Staff_Group',
                'Bass_Clarinet_Music_Staff',
                'Bass_Clarinet_Music_Voice',
                'Bass_Clarinet_Rest_Voice',
                'Violin_Staff_Group',
                'Violin_RH_Music_Staff',
                'Violin_RH_Music_Voice',
                'Violin_Music_Staff',
                'Violin_Music_Voice',
                'Violin_Rest_Voice',
                'Viola_Staff_Group',
                'Viola_RH_Music_Staff',
                'Viola_RH_Music_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Staff_Group',
                'Cello_RH_Music_Staff',
                'Cello_RH_Music_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [35],
            ),
        ('duration', "1'04''"),
        ('final_measure_number', 51),
        ('first_measure_number', 35),
        ('segment_name', 'C'),
        ('segment_number', 4),
        ('start_clock_time', "3'00''"),
        ('stop_clock_time', "4'04''"),
        (
            'time_signatures',
            [
                '7/4',
                '4/4',
                '4/4',
                '3/4',
                '1/6',
                '4/4',
                '4/4',
                '3/4',
                '1/6',
                '4/4',
                '4/4',
                '3/4',
                '1/6',
                '4/4',
                '4/4',
                '3/4',
                '1/6',
                ],
            ),
        ]
    )
