import abjad


metadata = abjad.OrderedDict(
    [
        (
            'bol_measure_numbers',
            [176, 189, 199],
            ),
        ('duration', "1'44''"),
        (
            'fermata_measure_numbers',
            [180, 183, 188, 193, 196, 207],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 207),
        ('first_measure_number', 176),
        ('segment_name', 'M'),
        ('segment_number', 14),
        ('start_clock_time', "13'16''"),
        ('stop_clock_time', "15'00''"),
        (
            'time_signatures',
            [
                '3/4',
                '4/4',
                '4/4',
                '2/4',
                '1/4',
                '7/4',
                '3/4',
                '1/4',
                '4/4',
                '3/4',
                '4/4',
                '3/4',
                '1/4',
                '2/4',
                '7/4',
                '7/4',
                '8/4',
                '1/4',
                '7/4',
                '3/4',
                '1/4',
                '2/4',
                '8/4',
                '7/4',
                '4/4',
                '4/4',
                '3/4',
                '7/4',
                '8/4',
                '3/4',
                '4/4',
                '1/4',
                ],
            ),
        ]
    )
