import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Ensemble_Staff_Group',
                'Bass_Clarinet_Music_Staff',
                'Bass_Clarinet_Music_Voice',
                'Bass_Clarinet_Rest_Voice',
                'Violin_Staff_Group',
                'Violin_RH_Music_Staff',
                'Violin_RH_Music_Voice',
                'Violin_Music_Staff',
                'Violin_Music_Voice',
                'Violin_Rest_Voice',
                'Viola_Staff_Group',
                'Viola_RH_Music_Staff',
                'Viola_RH_Music_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Staff_Group',
                'Cello_RH_Music_Staff',
                'Cello_RH_Music_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [10, 23],
            ),
        ('duration', "2'04''"),
        (
            'fermata_measure_numbers',
            [13, 15, 19, 21, 25, 27, 34],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 34),
        ('first_measure_number', 10),
        ('segment_name', 'B'),
        ('segment_number', 3),
        ('start_clock_time', "0'56''"),
        ('stop_clock_time', "3'00''"),
        (
            'time_signatures',
            [
                '4/4',
                '4/4',
                '3/4',
                '1/4',
                '7/4',
                '1/4',
                '8/4',
                '3/4',
                '4/4',
                '1/4',
                '4/4',
                '1/4',
                '2/4',
                '7/4',
                '3/4',
                '1/4',
                '4/4',
                '1/4',
                '3/4',
                '4/4',
                '3/4',
                '2/4',
                '7/4',
                '8/4',
                '1/4',
                ],
            ),
        ]
    )
