import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Ensemble_Staff_Group',
                'Bass_Clarinet_Music_Staff',
                'Bass_Clarinet_Music_Voice',
                'Bass_Clarinet_Rest_Voice',
                'Violin_Staff_Group',
                'Violin_RH_Music_Staff',
                'Violin_RH_Music_Voice',
                'Violin_Music_Staff',
                'Violin_Music_Voice',
                'Viola_Staff_Group',
                'Viola_RH_Music_Staff',
                'Viola_RH_Music_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Cello_Staff_Group',
                'Cello_RH_Music_Staff',
                'Cello_RH_Music_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [87],
            ),
        ('duration', "0'59''"),
        ('final_measure_number', 98),
        ('first_measure_number', 87),
        ('segment_name', 'G'),
        ('segment_number', 8),
        ('start_clock_time', "6'55''"),
        ('stop_clock_time', "7'54''"),
        (
            'time_signatures',
            [
                '7/4',
                '1/6',
                '7/4',
                '1/6',
                '7/4',
                '1/6',
                '7/4',
                '1/6',
                '7/4',
                '1/6',
                '7/4',
                '1/6',
                ],
            ),
        ]
    )
